server:
    port: 8761

spring:
    application:
        name: eureka.server
    config:
        import: "configserver:http://localhost:4444"
eureka:
    client:
        register-with-eureka: true #util para configuración por clusters (true para registro de varios clientes eureka). Inicialmente será false para que el servidor no se registre asi mismo como microservicio
        fetch-registry: false #no necesita cachear en local la información proporcionada por el servidor ya que es el servidor mismo (no hay otro eureka)

        service-url:
            defaultZone: http://localhost:8761/eureka/


